spring.profiles.default=dev

# Local/dev S3 defaults
app.s3.internal-endpoint=${S3_ENDPOINT_INTERNAL:http://localhost:9000}
app.s3.public-endpoint=${S3_ENDPOINT_PUBLIC:http://localhost:9000}

spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:minioadmin}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:minioadmin}
spring.cloud.aws.region.static=${AWS_REGION:ap-northeast-2}
spring.cloud.aws.s3.bucket=${S3_BUCKET:book-wheel-images-purple-project}
spring.cloud.aws.s3.endpoint=${S3_ENDPOINT_INTERNAL:http://localhost:9000}
spring.cloud.aws.s3.path-style-access-enabled=true
